image: node:latest

stages:
- build

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - cd client
    - cat $NG_CONFIG >> "$(pwd)/src/environments/config.ts"
    - npm install
    - npm install -g @angular/cli
    - ng build --aot --prod
    
  artifacts:
    paths:
    - client/dist/srtt/

